APP_IMAGE_NAME := transaction-temporal-workflow/transaction-pubsub:latest
APP_NAME := transaction-pubsub
APP_DIR := cmd/pubsub/transaction

include ../../../script/docker.Makefile
include ../../../script/kubernetes.Makefile
