APP_IMAGE_NAME := temporalio-poc/transaction-pubsub:latest
APP_NAME := transaction-pubsub
APP_DIR := cmd/pubsub/transaction
APP_TYPE := pubsub

include ../../../script/docker.Makefile
include ../../../script/kubernetes.Makefile
