version: "3.5"
services:
  transaction-server:
    container_name: transaction-server
    image: temporalio-poc/transaction-server:latest
    network_mode: host
    env_file:
      - cmd/server/transaction/.env

  transaction-worker:
    container_name: transaction-worker
    image: temporalio-poc/transaction-worker:latest
    network_mode: host
    env_file:
      - cmd/worker/transaction/.env

  transaction-pubsub:
    container_name: transaction-pubsub
    image: temporalio-poc/transaction-pubsub:latest
    network_mode: host
    env_file:
      - cmd/pubsub/transaction/.env

  transaction-cron:
    container_name: transaction-cron
    image: temporalio-poc/transaction-cron:latest
    network_mode: host
    env_file:
      - cmd/cron/transaction/.env

  user-worker:
    container_name: user-worker
    image: temporalio-poc/user-worker:latest
    network_mode: host
    env_file:
      - cmd/worker/user/.env

  user-pubsub:
    container_name: user-pubsub
    image: temporalio-poc/user-pubsub:latest
    network_mode: host
    env_file:
      - cmd/pubsub/user/.env

  user-cron:
    container_name: user-cron
    image: temporalio-poc/user-cron:latest
    network_mode: host
    env_file:
      - cmd/cron/user/.env
