APP_IMAGE_NAME := transaction-temporal-workflow/user-worker:latest
APP_NAME := user-worker
APP_DIR := cmd/worker/user
APP_TYPE := worker

include ../../../script/docker.Makefile
include ../../../script/kubernetes.Makefile
