APP_IMAGE_NAME := temporalio-poc/transaction-cron:latest
APP_NAME := transaction-cron
APP_DIR := cmd/cron/transaction
APP_TYPE := cron

include ../../../script/docker.Makefile
include ../../../script/kubernetes.Makefile
