APP_IMAGE_NAME := transaction-temporal-workflow/transaction-cron:latest
APP_NAME := transaction-cron
APP_DIR := cmd/cron/transaction

include ../../../script/docker.Makefile
include ../../../script/kubernetes.Makefile
