APP_IMAGE_NAME := transaction-temporal-workflow/user-cron:latest
APP_NAME := user-cron
APP_DIR := cmd/cron/user
APP_TYPE := cron

include ../../../script/docker.Makefile
include ../../../script/kubernetes.Makefile
