// @generated by protoc-gen-connect-es v0.8.0 with parameter "target=ts"
// @generated from file api/transaction.proto (package transaction_temporal_workflow.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateTransactionRequest, CreateTransactionResponse, ProcessTransactionRequest, ProcessTransactionResponse } from "./transaction_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service transaction_temporal_workflow.api.Transaction
 */
export const Transaction = {
  typeName: "transaction_temporal_workflow.api.Transaction",
  methods: {
    /**
     * @generated from rpc transaction_temporal_workflow.api.Transaction.CreateTransaction
     */
    createTransaction: {
      name: "CreateTransaction",
      I: CreateTransactionRequest,
      O: CreateTransactionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc transaction_temporal_workflow.api.Transaction.ProcessTransaction
     */
    processTransaction: {
      name: "ProcessTransaction",
      I: ProcessTransactionRequest,
      O: ProcessTransactionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

