apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname-deployment
  labels:
    app: appname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appname
  template:
    metadata:
      labels:
        app: appname
    spec:
      containers:
        - name: appname
          image: docker.io/appimagename
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
