auth:
  enabled: true
  password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
master:
  persistence:
    enabled: false
    existingClaim: redis-pv-claim
volumePermissions:
  enabled: true
replica:
  replicaCount: 0
