APP_IMAGE_NAME := temporalio-poc/transaction-worker:latest
APP_NAME := transaction-worker
APP_DIR := cmd/worker/transaction
APP_TYPE := worker

include ../../../script/docker.Makefile
include ../../../script/kubernetes.Makefile
