APP_IMAGE_NAME := transaction-temporal-workflow/transaction-server:latest
APP_NAME := transaction-server
APP_DIR := cmd/server/transaction

include ../../../script/docker.Makefile
include ../../../script/kubernetes.Makefile
