APP_IMAGE_NAME := temporalio-poc/transaction-server:latest
APP_NAME := transaction-server
APP_DIR := cmd/server/transaction
APP_TYPE := server

include ../../../script/docker.Makefile
include ../../../script/kubernetes.Makefile
