APP_IMAGE_NAME := transaction-temporal-workflow/user-pubsub:latest
APP_NAME := user-pubsub
APP_DIR := cmd/pubsub/user
APP_TYPE := pubsub

include ../../../script/docker.Makefile
include ../../../script/kubernetes.Makefile
